### PR TITLE
add placeholder text to some forms fields; minor tweaks to language

### PR DESCRIPTION
**Pull request by brahn**
Tiny bit of text bikeshedding for clarity/readability. Screenshot of the results:

pledge never again 2016-12-17 16-16-38

### CODE REVIEW

**Comment by lizthegrey** [comment]
This needs to also say it's okay to list your Title/Profession as your 'title/role' if you're not employed or don't want to list your specific employer. but I know that's a mouthful.

**Comment by brahn** [comment]
ah, great point. updated.

**Comment by brahn** [comment]
pledge never again 2016-12-17 20-19-19

**Comment by lizthegrey** [comment]
I will push this tomorrow morning - 11pm is never a great time to push changes to a prod system.

**Comment by brahn** [comment]
Indeed :-) Entirely at your convenience, and thanks!

**Pull request merged**
